name: my_custom_textfield
description:  The 'my_custom_textfield' package provides a customizable text field widget for Flutter applications. This widget is designed to enhance the user input experience with features like customizable hint text, prefix icons, and input validation. Ideal for developers looking to implement consistent and stylish text fields across their apps, the 'CustomTextfield' widget supports various input types and formats, ensuring flexibility and ease of use.
version: 1.0.1
repository: https://github.com/Aabdulloh2005/my_custom_textfield.git

environment:
  sdk: '>=3.3.4 <4.0.0'

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  # path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  lints: ^3.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true